---
title: "Modelo_fase_cv"
author: "Zaïra Méndez"
date: "2025-06-18"
output: html_document
---

```{r}
library(R2WinBUGS)
library(dplyr)
```

#MODELO WINBUGS
```{r}
modelo <- function() {
  for (i in 1:n) {

    # Parte 1: Rage
    Rage[i] ~ dbeta(alpha_f[i], beta_f[i])
    alpha_f[i] <- mu_f[i]*phi_f
    beta_f[i] <- (1 - mu_f[i])*phi_f
    logit(mu_f[i]) <- beta0_f + beta1_f[Sexo[i]] + beta2_f[fase[i]] + b.indiv_f[Usuario[i]]

    # Parte 2: AU04
    Media_meanAU4[i] ~ dbeta(alpha_c[i], beta_c[i])
    alpha_c[i] <- mu_c[i]*phi_c
    beta_c[i] <- (1 - mu_c[i])*phi_c
    logit(mu_c[i]) <- beta0_c + beta3_c*Rage[i] + beta1_c[Sexo[i]] + beta2_c[fase[i]]

    # Parte 3: AU12
    Media_meanAU12[i] ~ dbeta(alpha_s[i], beta_s[i])
    alpha_s[i] <- mu_s[i]*phi_s
    beta_s[i] <- (1 - mu_s[i])*phi_s
    logit(mu_s[i]) <- beta0_s + beta3_s*Rage[i] + beta1_s[Sexo[i]] + beta2_s[fase[i]]

    # Parte 4: AU24
    Media_meanAU24[i] ~ dbeta(alpha_l[i], beta_l[i])
    alpha_l[i] <- mu_l[i]*phi_l
    beta_l[i] <- (1 - mu_l[i])*phi_l
    logit(mu_l[i]) <- beta0_l + beta3_l*Rage[i] + beta1_l[Sexo[i]] + beta2_l[fase[i]]

    # Parte 5: AU05
    Media_meanAU5[i] ~ dbeta(alpha_p[i], beta_p[i])
    alpha_p[i] <- mu_p[i]*phi_p
    beta_p[i] <- (1 - mu_p[i])*phi_p
    logit(mu_p[i]) <- beta0_p + beta3_p*Rage[i] + beta1_p[Sexo[i]] + beta2_p[fase[i]]
  }

  # Priors 
  beta0_f ~ dnorm(0, 0.01)
  beta0_c ~ dnorm(0, 0.01); beta3_c ~ dnorm(0, 0.01)
  beta0_s ~ dnorm(0, 0.01); beta3_s ~ dnorm(0, 0.01)
  beta0_l ~ dnorm(0, 0.01); beta3_l ~ dnorm(0, 0.01)
  beta0_p ~ dnorm(0, 0.01); beta3_p ~ dnorm(0, 0.01)

  # Efectos fijos (sexo: por defecto mujer)
  beta1_f[1] <- 0; beta1_f[2] ~ dnorm(0, 0.01)
  beta1_c[1] <- 0; beta1_c[2] ~ dnorm(0, 0.01)
  beta1_s[1] <- 0; beta1_s[2] ~ dnorm(0, 0.01)
  beta1_l[1] <- 0; beta1_l[2] ~ dnorm(0, 0.01)
  beta1_p[1] <- 0; beta1_p[2] ~ dnorm(0, 0.01)

  # Efectos fijos (fase: por defecto basal)
  beta2_f[1] <- 0; beta2_f[2] ~ dnorm(0, 0.01)
  beta2_c[1] <- 0; beta2_c[2] ~ dnorm(0, 0.01)
  beta2_s[1] <- 0; beta2_s[2] ~ dnorm(0, 0.01)
  beta2_l[1] <- 0; beta2_l[2] ~ dnorm(0, 0.01)
  beta2_p[1] <- 0; beta2_p[2] ~ dnorm(0, 0.01)

  # Efectos aleatorios
  for (k in 1:34) {
    b.indiv_f[k] ~ dnorm(0, tau.indiv_f)
  }

  tau.indiv_f <- pow(sd.indiv_f, -2)
  sd.indiv_f ~ dunif(0, 1000)

  # Priors para phi
  phi_f ~ dgamma(1, 0.1)
  phi_c ~ dgamma(1, 0.1)
  phi_s ~ dgamma(1, 0.1)
  phi_l ~ dgamma(1, 0.1)
  phi_p ~ dgamma(1, 0.1)
}

# Datos
datos <- list(
  Rage = pmin(pmax(datosnew$Rage, 0.0001), 0.9999),
  Media_meanAU4 = datosnew$AU04_Mean,
  Media_meanAU12 = datosnew$AU12_Mean,
  Media_meanAU24 = datosnew$AU24_Mean,
  Media_meanAU5 = datosnew$AU05_Mean,
  Sexo = as.numeric(datosnew$Sex),
  fase = as.numeric(as.factor(datosnew$Phase)),
  Usuario = datosnew$User,
  n = dim(datosnew)[1]
)

# Iniciales
iniciales <- function() {
  list(
    beta0_f = rnorm(1),
    beta0_c = rnorm(1), beta3_c = rnorm(1),
    beta0_s = rnorm(1), beta3_s = rnorm(1),
    beta0_l = rnorm(1), beta3_l = rnorm(1),
    beta0_p = rnorm(1), beta3_p = rnorm(1),
    beta1_f = c(NA, rnorm(1)), beta1_c = c(NA, rnorm(1)), beta1_s = c(NA, rnorm(1)),
    beta1_l = c(NA, rnorm(1)), beta1_p = c(NA, rnorm(1)),
    beta2_f = c(NA, rnorm(1)), beta2_c = c(NA, rnorm(1)), beta2_s = c(NA, rnorm(1)),
    beta2_l = c(NA, rnorm(1)), beta2_p = c(NA, rnorm(1)),
    sd.indiv_f = runif(1, 0, 100),
    b.indiv_f = rnorm(34, 0, 1),
    phi_f = rgamma(1, 1, 0.1),
    phi_c = rgamma(1, 1, 0.1),
    phi_s = rgamma(1, 1, 0.1),
    phi_l = rgamma(1, 1, 0.1),
    phi_p = rgamma(1, 1, 0.1)
  )
}

# Parámetros a monitorizar
param <- c("beta0_f", "beta0_c", "beta3_c", "beta0_s", "beta3_s", "beta0_l", "beta3_l", "beta0_p", "beta3_p",
           "beta1_f", "beta1_c", "beta1_s", "beta1_l", "beta1_p",
           "beta2_f", "beta2_c", "beta2_s", "beta2_l", "beta2_p",
           "phi_f", "phi_c", "phi_s", "phi_l", "phi_p",
           "b.indiv_f", "sd.indiv_f")

# Modelo WinBUGS
modelo_cvfase <- bugs(
  data = datos,
  inits = iniciales,
  parameters = param,
  model = modelo,
  bugs.directory = "C:/Users/crist/OneDrive/Escritorio/MASTER_BIO/PRIMER CURSO/CUARTO MÓDULO/MJB/WinBUGS14/WinBUGS14",
  n.iter = 4000000,
  n.burnin = 500000,
  n.thin = 1300,
  debug = TRUE
)


summary_modelo <- round(modelo_cvfase$summary, 2)

```

#DISTRIBUCIÓN A POSTERIORI DE MU_F
```{r}
# Extraer parámetros del modelo
beta0_e     <- modelo_cvfase$sims.list$beta0_e
b_hombre_e  <- modelo_cvfase$sims.list$b.hombre_e
b_fase_e    <- modelo_cvfase$sims.list$b.fase_e
b_indiv_e   <- modelo_cvfase$sims.list$b.indiv_e  # matriz [n_iter × n_indiv]

n_iter <- length(beta0_e)
n_indiv <- ncol(b_indiv_e)

# Obtener sexo por individuo (usuario)
indiv_info <- datosnew %>%
  distinct(User, Sex) %>%
  arrange(User) %>%
  slice(1:n_indiv)

# Convertimos el sexo a "Masculino"/"Femenino"
sexo_indiv <- ifelse(indiv_info$Sex == "M", "Masculino", "Femenino")

# Inicializar dataframe
df_mu <- data.frame()

# Fases
fases <- c("Basal", "Provocación")

# Loop por individuo y fase
for (k in 1:n_indiv) {
  is_male <- ifelse(sexo_indiv[k] == "Masculino", 1, 0)

  for (fase in fases) {
    is_provoc <- ifelse(fase == "Provocación", 1, 0)

    logit_mu <- beta0_e +
      is_male * b_hombre_e +
      is_provoc * b_fase_e +
      b_indiv_e[, k]

    mu_k <- 1 / (1 + exp(-logit_mu))

    df_mu <- rbind(df_mu, data.frame(
      mu = mu_k,
      Sexo = sexo_indiv[k],
      Fase = fase,
      Individuo = paste0("Indiv_", k)
    ))
  }
}


```

#PREDICTIVA PARA HOMBRE Y MUJER CON FASE BASAL Y PROVOCACIÓN
```{r}
predictiva_condicional <- function(modelo, sexo = c("mujer", "hombre"), fase = c("basal", "provocacion")) {
  inv_logit <- function(x) 1 / (1 + exp(-x))
  sexo <- match.arg(sexo)
  fase <- match.arg(fase)
  
  # Extraer cadenas base Y_F
  beta0_f    <- modelo$sims.list$beta0_e        
  phi_f      <- modelo$sims.list$phi_e          
  sd_indiv_f <- modelo$sims.list$sd.indiv_e     
  n_sims <- length(beta0_f)
  
  # Efectos sexo y fase en Y_F
  b_hombre_f <- if(sexo == "hombre") modelo$sims.list$b.hombre_e else rep(0, n_sims)
  b_fase_f   <- if(fase == "provocacion") modelo$sims.list$b.fase_e else rep(0, n_sims)
  
  # Efecto aleatorio
  set.seed(123)
  b_f <- rnorm(n_sims, mean = 0, sd = sd_indiv_f)
  
  # Logit mu Y_F
  logit_mu_f <- beta0_f + b_f + b_hombre_f + b_fase_f
  mu_f <- inv_logit(logit_mu_f)
  alpha_f <- mu_f * phi_f
  beta_f <- (1 - mu_f) * phi_f
  set.seed(123)
  yF_pred <- rbeta(n_sims, alpha_f, beta_f)
  
  # Extraer coeficientes gestos
  beta0_c <- modelo$sims.list$beta0_c
  beta0_s <- modelo$sims.list$beta0_l
  beta0_l <- modelo$sims.list$beta0_k
  beta0_p <- modelo$sims.list$beta0_p
  
  beta1_c <- if(sexo == "hombre") modelo$sims.list$b.hombre_c else rep(0, n_sims)
  beta1_s <- if(sexo == "hombre") modelo$sims.list$b.hombre_l else rep(0, n_sims)
  beta1_l <- if(sexo == "hombre") modelo$sims.list$b.hombre_k else rep(0, n_sims)
  beta1_p <- if(sexo == "hombre") modelo$sims.list$b.hombre_p else rep(0, n_sims)
  
  beta2_c <- if(fase == "provocacion") modelo$sims.list$b.fase_c else rep(0, n_sims)
  beta2_s <- if(fase == "provocacion") modelo$sims.list$b.fase_l else rep(0, n_sims)
  beta2_l <- if(fase == "provocacion") modelo$sims.list$b.fase_k else rep(0, n_sims)
  beta2_p <- if(fase == "provocacion") modelo$sims.list$b.fase_p else rep(0, n_sims)
  
  beta3_c <- modelo$sims.list$beta1_c
  beta3_s <- modelo$sims.list$beta1_l
  beta3_l <- modelo$sims.list$beta1_k
  beta3_p <- modelo$sims.list$beta1_p
  
  phi_c <- modelo$sims.list$phi_c
  phi_s <- modelo$sims.list$phi_l
  phi_l <- modelo$sims.list$phi_k
  phi_p <- modelo$sims.list$phi_p
  
  # Calcular gestos
  logit_mu_c <- beta0_c + beta1_c + beta2_c + beta3_c * yF_pred
  mu_c <- inv_logit(logit_mu_c)
  alpha_c <- mu_c * phi_c
  beta_c <- (1 - mu_c) * phi_c
  yC_pred <- rbeta(n_sims, alpha_c, beta_c)
  
  logit_mu_s <- beta0_s + beta1_s + beta2_s + beta3_s * yF_pred
  mu_s <- inv_logit(logit_mu_s)
  alpha_s <- mu_s * phi_s
  beta_s <- (1 - mu_s) * phi_s
  yS_pred <- rbeta(n_sims, alpha_s, beta_s)
  
  logit_mu_l <- beta0_l + beta1_l + beta2_l + beta3_l * yF_pred
  mu_l <- inv_logit(logit_mu_l)
  alpha_l <- mu_l * phi_l
  beta_l <- (1 - mu_l) * phi_l
  yL_pred <- rbeta(n_sims, alpha_l, beta_l)
  
  logit_mu_p <- beta0_p + beta1_p + beta2_p + beta3_p * yF_pred
  mu_p <- inv_logit(logit_mu_p)
  alpha_p <- mu_p * phi_p
  beta_p <- (1 - mu_p) * phi_p
  yP_pred <- rbeta(n_sims, alpha_p, beta_p)
  
  # Dataframe final
  data.frame(
    Y_F = yF_pred,
    Y_C = yC_pred,
    Y_S = yS_pred,
    Y_L = yL_pred,
    Y_P = yP_pred
  )
}
```

```{r}
# Mujer Basal
df_mujer_basal <- predictiva_condicional(modelo_cvfase, sexo = "mujer", fase = "basal")

# Hombre Basal
df_hombre_basal <- predictiva_condicional(modelo_cvfase, sexo = "hombre", fase = "basal")

# Mujer Provocación
df_mujer_provocacion <- predictiva_condicional(modelo_cvfase, sexo = "mujer", fase = "provocacion")

# Hombre Provocación
df_hombre_provocacion <- predictiva_condicional(modelo_cvfase, sexo = "hombre", fase = "provocacion")

```

```{r}
analizar_condicional_boxplot(df_mujer_basal,       "Y_P")
analizar_condicional_boxplot(df_hombre_basal,      "Y_C")
analizar_condicional_boxplot(df_mujer_provocacion, "Y_P")
analizar_condicional_boxplot(df_hombre_provocacion,"Y_C")

```

